name: Deploy to HuggingFace Spaces

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub
      
      - name: Login to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HUGGINGFACE_HUB_TOKEN }}
        run: |
          python -c "from huggingface_hub import login; login('$HF_TOKEN')"
        
      - name: Deploy to Hugging Face Spaces
        env:
          HF_USERNAME: fartec0
          HF_SPACE_NAME: AI-testing-portal
        run: |
          cp app/app.py app.py || true  # Copy app file if necessary
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          echo "Pushing to Hugging Face Space..."
          git push https://huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME main:main -f
